### PR TITLE
Add wrappers for cu/hipsparse to hic

### PR DESCRIPTION
**Pull request by l90lpa**
This PR adds wrappers for parts of cuSparse and hipSparse to hic.

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/atlas?pullRequest=237) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/atlas?pullRequest=237) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/atlas?pullRequest=237) it.</sub>

**Comment by wdeconinck** [comment]
Hi @l90lpa this looks great, thanks!
I would probably make  hicsparse a separate cmake target though to have the choice if a downstream target will actually link with cusparse or hipsparse.

**Comment by wdeconinck** [comment]
I rebased on latest develop and did minor changes. I think this is now good to merge.

**Comment by wdeconinck** [comment]
This was tested successfully on LUMI. Thanks @l90lpa !

**Pull request merged**
