### PR TITLE
Added (lon, lat) to (alpha, beta) transforms to cubed sphere projection

### LINKED ISSUE #115: Add (lon, lat) to (alpha, beta) transforms to cubed sphere projection
We need to add some additional functionality to the cubed-sphere projection due to incompatibilities the current projection and the interpolation framework in https://github.com/JCSDA-internal/oops.

Specifically, we need to add some functionality to convert between (_lon_, _lat_) and (_alpha_, _beta_) for _any_ cubed sphere panel/tile _t_. Currently the projection forces a strict mapping from (_lon_, _lat_) to a specific _t_.

### PR DESCRIPTION
**Pull request by odlomax**
This PR adds (lon, lat) <-> (alpha, beta) transforms to the cubed sphere projection. This resolve a conflict between the cubed sphere interpolation class and the method of redistribution data in JCSDA-internal/oops.

This closes #115 and addresses [lfric-lite-jedi #195](https://github.com/JCSDA-internal/lfric-lite-jedi/issues/195).

Projection tests are added to Atlas via this PR. Further interpolation examples are shown in [PR lfric-lite-jedi #200](https://github.com/JCSDA-internal/lfric-lite-jedi/pull/200).

### CODE REVIEW

**Comment by wdeconinck** [comment]
Thanks @odlomax , it is good to have another excellent contribution without anything to remark :)

**Comment by odlomax** [comment]
> Thanks @odlomax , it is good to have another excellent contribution without anything to remark :)

Thanks, @wdeconinck. You are too kind with your words! 😁

**Comment by odlomax** [comment]
@wdeconinck, would it be possible to get a tag from this merge?

**Comment by odlomax** [comment]
> > @wdeconinck, would it be possible to get a tag from this merge?
> 
> 0.32.1

Today has been a good day.

**Pull request merged**
