### PR TITLE
Interpolation succeeds when no target points

### PR DESCRIPTION
**Pull request by twsearle**
The interpolator is sometimes called when there are no target points. This is particularly a concern when running interpolations to PointCloud function spaces. For example, under some MPI decompositions, a processor might have no interpolation target locations within its domain because there happen to be no observations in that region in this run.

Without the following changes, interpolating a target field with no target points will cause an error when an eckit::SparseMatrix is constructed. See [eckit/linalg/SparseMatrix#L215](https://github.com/ecmwf/eckit/blob/develop/src/eckit/linalg/SparseMatrix.cc#L215). This change allows the unstructured_bilinear_lonlat interpolator to exit early without adding data to the matrix. When the interpolation is executed it will also end early if there are no target points to interpolate.

### CODE REVIEW

**Comment by twsearle** [comment]
Sure, no problem! I have added a test interpolating to a PointCloud with no target points.

**Comment by DJDavies2** [comment]
I am getting a failure when running this branch for test atlas_test_trace:

Running 4 tests:
Running case 0: test elapsed ...
Completed case 0: test elapsed
Running case 1: test trace OpenMP ...
*** Error in `/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace': double free or corruption (fasttop): 0x00002ac9f00009b0 ***
======= Backtrace: =========
/usr/lib64/libc.so.6(+0x81329)[0x2ac9e14cf329]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace(_ZN9__gnu_cxx13new_allocatorISt10_List_nodeImEE10deallocateEPS2_m+0x20)[0x422734]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace(_ZNSt16allocator_traitsISaISt10_List_nodeImEEE10deallocateERS2_PS1_m+0x2b)[0x42153a]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace(_ZNSt7__cxx1110_List_baseImSaImEE11_M_put_nodeEPSt10_List_nodeImE+0x28)[0x41fef4]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace(_ZNSt7__cxx114listImSaImEE8_M_eraseESt14_List_iteratorImE+0x6f)[0x4227a7]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/lib/libatlas.so.0.29(_ZNSt7__cxx114listImSaImEE9pop_frontEv+0x2a)[0x2ac9dea61f2c]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/lib/libatlas.so.0.29(_ZN5atlas7runtime5trace9CallStack9pop_frontEv+0x18)[0x2ac9dea61d20]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace(_ZN5atlas7runtime5trace16CurrentCallStack3popEv+0x21)[0x41aee3]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace(_ZN5atlas7runtime5trace6TraceTINS1_11TraceTraitsEE4stopEv+0x40)[0x41e82c]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace[0x41a450]
/home/h03/darth/srv/bb-jedi-dependencies/spice_intel-v7/lib64/libgomp.so.1(GOMP_parallel_loop_guided+0x25)[0x2ac9df4ba235]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace(_ZN5atlas4test14traced_test_55ERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERii+0x4a)[0x418e01]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace(_ZN5atlas4test7test_55ERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERii+0x179)[0x418c4e]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace(_ZNSt17_Function_handlerIFvRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERiiEPS8_E9_M_invokeERKSt9_Any_dataS6_S7_Oi+0x60)[0x41f0a1]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace(_ZNKSt8functionIFvRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERiiEEclES6_S7_i+0x75)[0x41d6f5]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace(_ZN5eckit7testing4Test3runENS0_13TestVerbosityERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS9_EE+0x8e)[0x41b2f8]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace(_ZN5eckit7testing3runERSt6vectorINS0_4TestESaIS2_EENS0_13TestVerbosityE+0x372)[0x41bf71]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace(_ZN5eckit7testing14run_tests_mainERSt6vectorINS0_4TestESaIS2_EEiPPcb+0xb0)[0x417180]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace(_ZN5eckit7testing9run_testsEiPPcb+0x31)[0x41724d]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace(_ZN5atlas4test3runINS0_20AtlasTestEnvironmentEEEiiPPc+0x3b)[0x41e39a]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace(_ZN5atlas4test3runEiPPc+0x20)[0x4180d2]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace(main+0x20)[0x41a0b3]
/usr/lib64/libc.so.6(__libc_start_main+0xf5)[0x2ac9e1470555]
/home/h01/frwd/cylc-run/atlas107/share/build-lfric-spice_intel_debug/atlas/src/tests/runtime/atlas_test_trace[0x416f89]

**Comment by wdeconinck** [comment]
> I am getting a failure when running this branch for test atlas_test_trace:

I don't see how this could be related to changes in this branch. Could you verify with the commit where the branch forked from?

**Comment by DJDavies2** [comment]
Yes you are correct, the failure is not related to this change.

**Comment by wdeconinck** [comment]
> Yes you are correct, the failure is not related to this change.

Thanks. I have just uploaded another commit (1872fbc1d) on the develop branch. Perhaps that avoids the issue?

**Comment by DJDavies2** [comment]
> > Yes you are correct, the failure is not related to this change.
> 
> Thanks. I have just uploaded another commit ([1872fbc](https://github.com/ecmwf/atlas/commit/1872fbc1d6ddd47d5d3b0f90d62092a1b30ff72a)) on the develop branch. Perhaps that avoids the issue?

Yes, the run seems to work now.

**Comment by wdeconinck** [comment]
Merged in develop with commit [565da20](https://github.com/ecmwf/atlas/commit/565da209df7cb0d4e13b4cc75dabe4b539083a46)

**Pull request closed without merging**
