### PR TITLE
Add Fortran bindings for creating lat/lon and Lambert regional grids

### PR DESCRIPTION
**Pull request by pmarguinaud**
Solves issue #23

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:80/ecmwf/atlas?pullRequest=24) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf/atlas?pullRequest=24) before we can accept your contribution.<br/><hr/>**Philippe Marguinaud** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf/atlas?pullRequest=24) it.</sub>

**Comment by wdeconinck** [comment]
Hi @pmarguinaud 
Do you know that it was already possible to create this with configuration objects?
See e.g. examples in
https://github.com/ecmwf/atlas/tree/develop/doc/example-grids

With the configuration approach and self registration of projections it is possible to easily extend Atlas with custom projections without creating interfaces. And hence avoiding a whole zoo of grid constructors for each projection.

I can understand though that it is a bit more cumbersome / error-prone to go through configurations.
In that spirit I want to propose something where we can compromise.
I started working on a following API, if you are happy with that:

**RotatedLonLat** 
```fortran
use atlas_module, Rotated => atlas_RotatedLonLatProjection
type(atlas_Grid) :: grid
grid = atlas_RegionalGrid( nx=11, ny=11, xy_min=[-5., -5.], xy_max=[5., 5.], &
     &     projection=Rotated(north_pole=[2.0, 46.7],rotation_angle=180.),
     &     y_numbering=+1 ) ! default negative
```
equivalent with following, where `north`, `west`, `south`, `east` are in "unrotated" reference
```fortran
use atlas_module, Rotated => atlas_RotatedLonLatProjection
type(atlas_Grid) :: grid
grid = atlas_RegionalGrid( nx=11, ny=11, north=5., west=-5., south=-5, east=5., &
     &     projection=Rotated(north_pole=[2.0, 46.7],rotation_angle=180.), ! optional
     &     y_numbering=+1 ) ! optional, default negative
```


**Lambert**
```fortran
use atlas_module, Lambert => atlas_LambertConformalConicProjection
type(atlas_Grid) :: grid
grid = atlas_RegionalGrid( nx=11, ny=11, dx=1000., dy=1000., xy_min=[-50000., -50000.], &
     &    projection=Lambert(4.0, 50.),
     &    y_numbering=+1 ) ! optional, default negative
```

To make sure that I am doing the right thing, and if it's not a problem, could you add a unit-test in the current PR that verifies a few coordinates and especially grid point numbering for one of your intended use cases for each?

**Comment by pmarguinaud** [comment]
Hello Willem,

I have added tests case for both lat/lon and Lambert grids. I hope that these tests fit your needs.

I will be perfectly happy with the approach you suggest.

Regards

**Comment by wdeconinck** [comment]
Thank you @pmarguinaud 
I have just added the above-mentioned API.
You can see it here:
https://github.com/ecmwf/atlas/blob/44bfec91238b63503f7dbfb18d86baddf650a55f/src/tests/grid/fctest_regional_grids.F90
I changed the default of "y_numbering" to be +1 for grids created using this constructor. I guess it makes more sense.

**Pull request closed without merging**
