### PR TITLE
add interface to adjoint of direct spectral transform - needs associated changes in ectrans

### PR DESCRIPTION
**Pull request by MarekWlasak**

### CODE REVIEW

**Comment by wdeconinck** [comment]
Hi @MarekWlasak Very Nice!
The associated ectrans change has been merged in ectrans and tagged with 1.1.0
Would you be able to add a test as well?

**Comment by MarekWlasak** [comment]
@wdeconinck - sure will do tomorrow!

**Comment by MarekWlasak** [comment]
@wdeconinck - tests have been added.

**Comment by wdeconinck** [comment]
Thank you @MarekWlasak for another excellent contribution!

**Pull request merged**
