### PR TITLE
gcc-10.1.0 Bugfix grid spacing missing string header

### PR DESCRIPTION
**Pull request by markjolah**
Missing `<string>` header is an error under gcc-10.1.0

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:80/ecmwf/atlas?pullRequest=51) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf/atlas?pullRequest=51) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: wdeconinck<br/>:white_check_mark: aerorahul<br/>:white_check_mark: benjaminmenetrier<br/>:x: markjolah<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf/atlas?pullRequest=51) it.</sub>

**Comment by markjolah** [comment]
Sorry, not sure how my one-line single-commit PR turned into 11 commits.  I think something is funny about how these cross-repo PRs work in github.

**Comment by wdeconinck** [comment]
Thanks for the PR. However could you please create the branch from this repo's develop branch instead?

**Comment by markjolah** [comment]
Did that fix it?  I added ecmwf as a remote and merged ecmwf/develop.

**Comment by wdeconinck** [comment]
The problem is that you started the branch from an existing JCSDA branch that has another history. I just cherry-picked your last commit to the develop branch.

**Pull request closed without merging**
