### PR TITLE
Feature/pointcloud extension

### PR DESCRIPTION
**Pull request by MarekWlasak**
This PR extends the PointCloud space to do halo exchange and adjoint halo exchange.  It is assumed that the partition and the remote index (as well as the ghost) are already allocated.

The code includes a test that demonstrates it working.

### CODE REVIEW

**Comment by DJDavies2** [comment]
I am getting a failure with this:

atlas_test_interpolation_grid_box_average:

Running 2 tests:
Running case 0: test_interpolation_grid_box_average ...
Running section "Earth's surface area using Field interpolation" ...
Integral A: 510101140207791.4, compared to 510101140207791.6 +- 1000, with relative error = 3.675741636719753e-16
Intersecting: 0.491998 second elapsed, 0.48 second cpu

[0] =========================================
[0] Segmentation fault (signal intercepted by atlas)
[0] -----------------------------------------
[0] BACKTRACE
[0] -----------------------------------------
[0] backtrace [1] stack has 27 addresses
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/lib/libeckit.so+eckit::BackTrace::dump[abi:cxx11]())0x48 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/lib/libatlas.so.0.30+atlas::backtrace[abi:cxx11]())0x18 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/lib/libatlas.so.0.30+atlas::library::atlas_signal_handler(int, siginfo_t*, void*))0x1bc 
[0] (/usr/lib64/libpthread.so.0+)0xf630 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/lib/libatlas.so.0.30+void atlas::parallel::HaloExchange::execute<double, 1, atlas::array::FirstDim>(atlas::array::Array&, bool) const)0x1ad 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/lib/libatlas.so.0.30+)0xb2438f 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/lib/libatlas.so.0.30+atlas::functionspace::detail::PointCloud::haloExchange(atlas::FieldSet const&, bool) const)0xb4 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/lib/libatlas.so.0.30+atlas::functionspace::detail::PointCloud::haloExchange(atlas::Field const&, bool) const)0x68 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/lib/libatlas.so.0.30+atlas::FunctionSpace::haloExchange(atlas::Field const&, bool) const)0x40 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/lib/libatlas.so.0.30+atlas::interpolation::Method::haloExchange(atlas::Field const&) const)0x6d 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/lib/libatlas.so.0.30+atlas::interpolation::Method::do_execute(atlas::Field const&, atlas::Field&, atlas::util::Metadata&) const)0xf7 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/lib/libatlas.so.0.30+atlas::interpolation::method::GridBoxAverage::do_execute(atlas::Field const&, atlas::Field&, atlas::util::Metadata&) const)0x117 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/lib/libatlas.so.0.30+atlas::interpolation::Method::execute(atlas::Field const&, atlas::Field&) const)0x118 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/lib/libatlas.so.0.30+atlas::Interpolation::execute(atlas::Field const&, atlas::Field&) const)0x3c 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/atlas/src/tests/interpolation/atlas_test_interpolation_grid_box_average+atlas::test::traced_test_67(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int&, int))0x83b 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/atlas/src/tests/interpolation/atlas_test_interpolation_grid_box_average+atlas::test::test_67(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int&, int))0x179 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/atlas/src/tests/interpolation/atlas_test_interpolation_grid_box_average+std::_Function_handler<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int&, int), void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int&, int)>::_M_invoke(std::_Any_data const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int&, int&&))0x60 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/atlas/src/tests/interpolation/atlas_test_interpolation_grid_box_average+std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int&, int)>::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int&, int) const)0x75 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/atlas/src/tests/interpolation/atlas_test_interpolation_grid_box_average+eckit::testing::Test::run(eckit::testing::TestVerbosity, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&))0x8e 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/atlas/src/tests/interpolation/atlas_test_interpolation_grid_box_average+eckit::testing::run(std::vector<eckit::testing::Test, std::allocator<eckit::testing::Test> >&, eckit::testing::TestVerbosity))0x372 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/atlas/src/tests/interpolation/atlas_test_interpolation_grid_box_average+eckit::testing::run_tests_main(std::vector<eckit::testing::Test, std::allocator<eckit::testing::Test> >&, int, char**, bool))0xb0 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/atlas/src/tests/interpolation/atlas_test_interpolation_grid_box_average+eckit::testing::run_tests(int, char**, bool))0x31 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/atlas/src/tests/interpolation/atlas_test_interpolation_grid_box_average+int atlas::test::run<atlas::test::AtlasTestEnvironment>(int, char**))0x3b 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/atlas/src/tests/interpolation/atlas_test_interpolation_grid_box_average+atlas::test::run(int, char**))0x20 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/atlas/src/tests/interpolation/atlas_test_interpolation_grid_box_average+main)0x20 
[0] (/usr/lib64/libc.so.6+__libc_start_main)0xf5 
[0] (/home/h01/frwd/cylc-run/atlas111/share/build-mo-spice_gnu_debug/atlas/src/tests/interpolation/atlas_test_interpolation_grid_box_average)

**Comment by DJDavies2** [comment]
Jobs are working now.

**Comment by wdeconinck** [comment]
Compile error here:
https://github.com/ecmwf/atlas/actions/runs/3183401764/jobs/5190568566#step:12:737

use instead `halo_exchange_.reset( new ... )` to be C++11 compliant

**Comment by wdeconinck** [comment]
Thanks @MarekWlasak this is great and squash-merged in develop with commit [442b771](https://github.com/ecmwf/atlas/commit/442b771f2f9ad905875f889343f2b803a532cc11)

**Comment by MarekWlasak** [comment]
@wdeconinck - thank you for putting it in! 😃

**Pull request closed without merging**
