### PR TITLE
Feature/cubed sphere dual mesh

### LINKED ISSUE #71: fatal error: atlas/library.h: No such file or directory and failed cmake run.
sudo ./build_hello_world.sh
Building project hello_world
+ mkdir -p /home/ian/ecmwfatlas/atlas/doc/example-projects/build_hello_world_2021-09-12_05-06-37
+ cd /home/ian/ecmwfatlas/atlas/doc/example-projects/build_hello_world_2021-09-12_05-06-37
+ cmake -DECBUILD_2_COMPAT=OFF /home/ian/ecmwfatlas/atlas/doc/example-projects/project_hello_world
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- atlas_VERSION           0.19.0
-- atlas_VERSION_STR       
-- atlas_DIR               /usr/lib/x86_64-linux-gnu/cmake/atlas_ecmwf
-- atlas_HAVE_OMP          1
-- atlas_HAVE_OMP_CXX      1
-- atlas_HAVE_OMP_Fortran  
-- atlas_HAVE_TRANS        
-- atlas_HAVE_MPI          
-- ATLAS_LIBRARIES         
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ian/ecmwfatlas/atlas/doc/example-projects/build_hello_world_2021-09-12_05-06-37
+ make
Scanning dependencies of target hello_world
[ 50%] Building CXX object CMakeFiles/hello_world.dir/hello_world.cc.o
/home/ian/ecmwfatlas/atlas/doc/example-projects/project_hello_world/hello_world.cc:1:10: fatal error: atlas/library.h: No such file or directory
    1 | #include "atlas/library.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/hello_world.dir/build.make:63: CMakeFiles/hello_world.dir/hello_world.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/hello_world.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
+ cleanup
+ EXIT_CODE=2
+ rm -Rf /home/ian/ecmwfatlas/atlas/doc/example-projects/build_hello_world_2021-09-12_05-06-37
+ exit 2
ian@ian-HP-Stream-Laptop-11-y0XX:~/ecmwfatlas/atlas/doc/example-projects$ ls
build_hello_world_fortran.sh  build_hello_world.sh  project_hello_world  project_hello_world_fortran  README  source-me.sh
ian@ian-HP-Stream-Laptop-11-y0XX:~/ecmwfatlas/atlas/doc/example-projects$ 

also
ian@ian-HP-Stream-Laptop-11-y0XX:~/ecmwfatlas$ cmake atlas
CMake Error at CMakeLists.txt:14 (find_package):
  Could not find a package configuration file provided by "ecbuild"
  (requested version 3.4) with any of the following names:

    ecbuildConfig.cmake
    ecbuild-config.cmake

  Add the installation prefix of "ecbuild" to CMAKE_PREFIX_PATH or set
  "ecbuild_DIR" to a directory containing one of the above files.  If
  "ecbuild" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!

### PR DESCRIPTION
**Pull request by odlomax**
This is an upstream copy of [this PR](https://github.com/JCSDA-internal/atlas/pull/80) which adds a cubed-sphere dual mesh generator to Atlas.

The dual mesh is tested with Atlas's interpolation class and is compatible with the `CubedSphereColumns` functionspace and redistribution methods.

## Original text follows:

This PR adds the cubed sphere-dual mesh generator to Atlas. This constructs a mesh by placing a node in each cell of a cubed-sphere mesh and connecting them together. The mesh halo size is currently limited to 1 (an exception is thrown if you try to supply a different size in the mesh generator config).

In addition, I have added and "array copier" helper struct and made some minor type-corrections to the cubed-sphere mesh generator.

A test is added which writes a test function to Gaussian grid field and interpolates it to a cubed-sphere dual mesh field. The the source Gaussian grid is partitioned using an equal bands partitioner. The target cubed-sphere is partitioned using a matching mesh partitioner (based on the source mesh).

Interpolated test pattern:
dual-interp

Cubed-sphere dual mesh partitioning:
dual-interp-part

Closes #71

### CODE REVIEW

**Comment by odlomax** [comment]
@wdeconinck I think the long list of commits reflects that fact that we're working off a slightly _tweaked_ fork of `ecmwf/develop`. I'm not seeing anything unexpected in the "files changed". @MarekWlasak we should probably aim to rebase our fork.

**Comment by odlomax** [comment]
Hi @wdeconinck,

I've updated the PR description to something more meaningful. If you have a general template you'd like us to follow, let me know.

Cheers,
@odlomax

**Comment by wdeconinck** [comment]
This PR has been squash-merged in develop with bad89e1
Thank you very much @odlomax for your contributions.

**Comment by odlomax** [comment]
@wdeconinck I promise not to have such a ridiculous commit history next time!

**Comment by wdeconinck** [comment]
Not a problem at all, it was more of an FYI  :-) .
It also allows me the opportunity to edit the commit message to link to an internal created JIRA issue as well as this PR,
and rebase changes on latest develop, etc.
The only downside is that Github marks it as "Closed" instead of "Merged", which is why I have the other Merged label added.

**Pull request closed without merging**
