### PR TITLE
Feature/cubed sphere structured functionspace

### PR DESCRIPTION
**Pull request by odlomax**
### This is a copy of [this PR](https://github.com/JCSDA-internal/atlas/pull/65). Updated original text is as follows:

I've made a functionspaces `CubedSphereCellCoumns` and `CubedSphereNodeColumns` which add a handful of methods to `CellColumns` and `NodeColumns`. It should make operations like interpolation significantly simpler. `CubedSphereCellCoumns` inherits two classes: `CellCoumns` and `CubedSphereStructure` (`CubedSphereNodeColumns` does the equivalent).

The new functionspaces have two important methods:

`idx_t index(idx_t t, idx_t i, idx_t j)` which converts an (t, i, j) triplet into a field index.

`void parallel_for(config, functor)` which traverses the functionspace, possibly skipping halos, and applies a functor. The functor should have the signature `f(idx_t index, idx_t t, idx_t i, idx_t j, idx_t k)`, `f(idx_t index, idx_t t, idx_t i, idx_t j)`, `f(idx_t index, idx_t k)` or `f(idx_t index)`.
If you're feeling a bit old fashioned, you could also perform a triple loop in (t, j, i) order and skip elements where index(t, i, j) == invalid_index(). However this should be avoided if possible, as it make assumptions on the memory layout of the mesh.

I've added mainly cosmetic minor changes to the cubed sphere mesh generator and utilities. This refactors "ijt" to "tij" and tweaks some the the interfaces accordingly. I also added more meaningful messages to some of the error traps.

### CODE REVIEW

**Comment by wdeconinck** [comment]
Hello @odlomax we finally got continuous integration back in business, and I spent some extra effort to now also have intel oneAPI compilers, alleviating my own tests on our internal systems.
I merged develop in your PR and the CI flagged that the **Release intel** build is failing for your new test. Could you have a look to have that fixed?

**Comment by odlomax** [comment]
> Hello @odlomax we finally got continuous integration back in business, and I spent some extra effort to now also have intel oneAPI compilers, alleviating my own tests on our internal systems. I merged develop in your PR and the CI flagged that the **Release intel** build is failing for your new test. Could you have a look to have that fixed?

Thanks, @wdeconinck . I'm having a look now. I suspect the error tolerance on some of the check was a bit too strict. I don't have an Intel environment set up, so I'll have to do a bit of trial and error with the CI.

**Comment by wdeconinck** [comment]
We just hit a problem that eckit, was just (2 hour ago) compiled with intel-oneAPI version "2021.3.x" and cached. The next run just now restarted with a new intel-oneAPI version "2021.4" and it seems incompatible :(
Some small things to sort out it seems to prevent this from happening in the future.
I will make small commit to workaround now

**Comment by odlomax** [comment]
> We just hit a problem that eckit, was just (2 hour ago) compiled with intel-oneAPI version "2021.3.x" and cached. The next run just now restarted with a new intel-oneAPI version "2021.4" and it seems incompatible :( Some small things to sort out it seems to prevent this from happening in the future. I will make small commit to workaround now

Oh no! No rest for the wicked, eh? ;)

**Comment by odlomax** [comment]
The board is green! Woohoo!

**Comment by wdeconinck** [comment]
> The board is green! Woohoo!

Running some internal CI and will squash-merge when all good.

**Comment by wdeconinck** [comment]
Thanks for the great work @odlomax 
This PR is squash-merged in develop with commit e725238c6944e5b5ad0f3df433d38f8c02528110
I had to apply some more minor fixes to get it to compile on our Cray compiler and older intel-19.

**Pull request closed without merging**
