### PR TITLE
Refactor `util::pack_vector_fields` to use `array::ArrayViewVariant`

### PR DESCRIPTION
**Pull request by odlomax**
This PR refactors `util::pack_vector_fields` to use `std::variant<ArrayViews...>` with `std::visit`, as opposed to nested `switch` statements to resolve the possible `Value` types and `Rank` values for different arrays.

I also found it beneficial to refactor `array::make_view_variant` such that it produces either a variant of `const` or a variant of `non- const` ArrayView types.

This PR needs #220 and #224 to be merged first.

### CODE REVIEW

**Comment by wdeconinck** [comment]
@odlomax Ready for rebase / conflict resolution

**Comment by odlomax** [comment]
Blimey, I didn't see that one coming...
https://github.com/ecmwf/atlas/actions/runs/11323604861/job/31488503545#step:14:3695

**Comment by wdeconinck** [comment]
> Blimey, I didn't see that one coming... https://github.com/ecmwf/atlas/actions/runs/11323604861/job/31488503545#step:14:3695

rerunning to see if it is a fluke

**Review by wdeconinck — APPROVED** [review]
All relevant tests have passed

**Pull request merged**
